export const alertConstants = {
    LOGIN_SUCCESS   : 'ALERT_LOGIN_SUCCESS',
    LOGIN_ERROR     : 'ALERT_LOGIN_ERROR',
    LOGOUT_SUCCESS  : 'ALERT_LOGOUT_SUCCESS',
    CLEAR           : 'ALERT_CLEAR',
    PROJECT_SUCCESS : 'ALERT_PROJECT_SUCCESS',
    PROJECT_ERROR   : 'ALERT_PROJECT_ERROR',
    MODAL_CLOSE     : 'ALERT_MODAL_CLOSE'
};

export const userConstants = {

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',

    USER_AUTH_SUCCESS: 'USER_AUTH_SUCCESS',

    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',

    PROFILE_SUCCESS: 'PROFILE_SUCCESS',

    LOGOUT: 'USERS_LOGOUT',

    CLEAR: 'ALERT_CLEAR'
}

export const projectConstants = {

    OPEN_PROJECTS: 'OPEN_PROJECTS'

}